# First Look at Data

In this notebook we explore the song data and do some remarks about
them, regarding data cleaning and modeling.

## 1. Initial set up

Cells below set up some variables (related to data directory, data set
URL and others) and modules required for the analysis to be performed in
the following parts of this notebook. Therefore, you may execute all the
cells in this section.

In [1]:
## python built-in modules
import sys
from pathlib import Path

## third party modules
import pandas as pd
import numpy  as np
import matplotlib.pyplot as plt

In [2]:
!pip3 install dotenv
!pip3 install loguru

Requirement already satisfied: dotenv in /home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (0.9.9)
Requirement already satisfied: python-dotenv in /home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (from dotenv) (1.1.1)
Requirement already satisfied: loguru in /home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages (0.7.3)

In [3]:
## retrives root path of the project
## resolve() obtains the absolute path and parents[1] goes back one
## directory
current_path = Path('.').resolve().parents[0]

## adds project root to path
sys.path.append(str(current_path))

In [4]:
## just showing that project root directory was added to python path
print(sys.path)

['/home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python312.zip', '/home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12', '/home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12/lib-dynload', '', '/home/gasobral/.config/jupyterlab-desktop/jlab_server/lib/python3.12/site-packages', '/home/gasobral/Meus Arquivos/data-science/music_popularity']

In [5]:
## loads specific package modules, which contain project settings
from music_popularity.config import PROCESSED_DATA_DIR
from music_popularity.config import RAW_DATA_DIR
from music_popularity.config import INTERIM_DATA_DIR

2025-08-03 16:11:01.549 | INFO     | music_popularity.config:<module>:11 - PROJ_ROOT path is: /home/gasobral/Meus Arquivos/data-science/music_popularity

# 2. Analysing the raw data

Previously we executed
[dataset.py](../music_popularity/music_popularitydataset.py) script to
download the data set from Kaggle.

In [7]:
for raw_file in RAW_DATA_DIR.iterdir():
    print(raw_file)

/home/gasobral/Meus Arquivos/data-science/music_popularity/data/raw/Most Streamed Spotify Songs 2024.csv
/home/gasobral/Meus Arquivos/data-science/music_popularity/data/raw/.gitkeep

In [8]:
raw_data = pd.read_csv(RAW_DATA_DIR / 'Most Streamed Spotify Songs 2024.csv',
                       encoding='latin_1')

In [9]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 29 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4600 non-null   object
 1   Album Name                  4600 non-null   object
 2   Artist                      4595 non-null   object
 3   Release Date                4600 non-null   object
 4   ISRC                        4600 non-null   object
 5   All Time Rank               4600 non-null   object
 6   Track Score                 4600 non-null   float64
 7   Spotify Streams             4487 non-null   object
 8   Spotify Playlist Count      4530 non-null   object
 9   Spotify Playlist Reach      4528 non-null   object
 10  Spotify Popularity          3796 non-null   float64
 11  YouTube Views               4292 non-null   object
 12  YouTube Likes               4285 non-null   object
 13  TikTok Posts                3427 non-null   object
 14  TikTok Likes                3620 non-null   object
 15  TikTok Views                3619 non-null   object
 16  YouTube Playlist Reach      3591 non-null   object
 17  Apple Music Playlist Count  4039 non-null   float64
 18  AirPlay Spins               4102 non-null   object
 19  SiriusXM Spins              2477 non-null   object
 20  Deezer Playlist Count       3679 non-null   float64
 21  Deezer Playlist Reach       3672 non-null   object
 22  Amazon Playlist Count       3545 non-null   float64
 23  Pandora Streams             3494 non-null   object
 24  Pandora Track Stations      3332 non-null   object
 25  Soundcloud Streams          1267 non-null   object
 26  Shazam Counts               4023 non-null   object
 27  TIDAL Popularity            0 non-null      float64
 28  Explicit Track              4600 non-null   int64
dtypes: float64(6), int64(1), object(22)
memory usage: 1.0+ MB

In [10]:
raw_data.head()

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",...,684,62.0,"17,598,718",114.0,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",...,3,67.0,"10,422,430",111.0,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",...,536,136.0,"36,321,847",172.0,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",...,"2,182",264.0,"24,684,248",210.0,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",...,1,82.0,"17,660,624",105.0,"4,493,884","7,006","207,179","457,017",NaN,1

We got an encoding error when executed *read_csv* for the first
time. Using *file*, we found the file is in latin-1 encoding
(iso-8859-1). That's why *encoding* was set to 'latin_1'. It is also
possible to use *iconv* to convert the file to utf-8, but we decided to
pass encoding argument to make explicit the file encoding.

Analysing column data, we propose the following dtypes for them.

In [35]:
## TODO fazer o mapeamento dos dados

In [11]:
raw_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Track Score,4600.0,41.844043,38.543766,19.4,23.3,29.9,44.425,725.4
Spotify Popularity,3796.0,63.501581,16.186438,1.0,61.0,67.0,73.000,96.0
Apple Music Playlist Count,4039.0,54.603120,71.612270,1.0,10.0,28.0,70.000,859.0
Deezer Playlist Count,3679.0,32.310954,54.274538,1.0,5.0,15.0,37.000,632.0
Amazon Playlist Count,3545.0,25.348942,25.989826,1.0,8.0,17.0,34.000,210.0
TIDAL Popularity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Explicit Track,4600.0,0.358913,0.479734,0.0,0.0,0.0,1.000,1.0

In [19]:
## show the porcentage of null values for each column
(raw_data.isna().sum() / raw_data.shape[0]) * 100

Track                           0.000000
Album Name                      0.000000
Artist                          0.108696
Release Date                    0.000000
ISRC                            0.000000
All Time Rank                   0.000000
Track Score                     0.000000
Spotify Streams                 2.456522
Spotify Playlist Count          1.521739
Spotify Playlist Reach          1.565217
Spotify Popularity             17.478261
YouTube Views                   6.695652
YouTube Likes                   6.847826
TikTok Posts                   25.500000
TikTok Likes                   21.304348
TikTok Views                   21.326087
YouTube Playlist Reach         21.934783
Apple Music Playlist Count     12.195652
AirPlay Spins                  10.826087
SiriusXM Spins                 46.152174
Deezer Playlist Count          20.021739
Deezer Playlist Reach          20.173913
Amazon Playlist Count          22.934783
Pandora Streams                24.043478
Pandora Track Stations         27.565217
Soundcloud Streams             72.456522
Shazam Counts                  12.543478
TIDAL Popularity              100.000000
Explicit Track                  0.000000
dtype: float64

We are discarting TIDAL Popularity column, since all their values are
null. For the remaining columns, we will check how null values affects
popularity prediction.

About duplicated values, only two records were found. You can find more
details below.

In [34]:
print(f'    Number of duplicated lines: {raw_data.duplicated().sum()}\n'
      f'Porcentage of duplicated lines: {raw_data.duplicated().sum() / raw_data.shape[0] * 100:.4f}%')

    Number of duplicated lines: 2
Porcentage of duplicated lines: 0.0435%

In [27]:
mask = raw_data.duplicated()
raw_data[mask]

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
2450,Tennessee Orange,Tennessee Orange,Megan Moroney,9/2/2022,TCAGJ2289254,"2,424",28.9,"227,893,586","28,139","12,480,714",...,34,5.0,"1,370",49.0,"56,972,562","26,968","1,336,043","708,143",NaN,0
3450,Dembow,Dembow,Danny Ocean,12/8/2017,USWL11700269,"3,441",23.3,"579,189,526","60,397","11,805,084",...,9,20.0,"37,649",12.0,"6,723,858","7,832",NaN,"1,619,550",NaN,0

In [30]:
mask = (raw_data['ISRC'] == 'TCAGJ2289254') | (raw_data['ISRC'] == 'USWL11700269')
raw_data[mask]

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
2449,Tennessee Orange,Tennessee Orange,Megan Moroney,9/2/2022,TCAGJ2289254,"2,424",28.9,"227,893,586","28,139","12,480,714",...,34,5.0,"1,370",49.0,"56,972,562","26,968","1,336,043","708,143",NaN,0
2450,Tennessee Orange,Tennessee Orange,Megan Moroney,9/2/2022,TCAGJ2289254,"2,424",28.9,"227,893,586","28,139","12,480,714",...,34,5.0,"1,370",49.0,"56,972,562","26,968","1,336,043","708,143",NaN,0
3447,Dembow,Dembow,Danny Ocean,12/8/2017,USWL11700269,"3,441",23.3,"579,189,526","60,397","11,805,084",...,9,20.0,"37,649",12.0,"6,723,858","7,832",NaN,"1,619,550",NaN,0
3450,Dembow,Dembow,Danny Ocean,12/8/2017,USWL11700269,"3,441",23.3,"579,189,526","60,397","11,805,084",...,9,20.0,"37,649",12.0,"6,723,858","7,832",NaN,"1,619,550",NaN,0